[project]

[project.name]
name = "itukarua"
location = "./"

[project.secrets]
SUPABASE_SERVICE_ROLE_KEY = ""

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323
enable_experimental_features = true

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true
enable_anonymous_signins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = true
secure_email_change_enabled = true
min_password_length = 6
password_requirements = ""

[auth.sms]
enabled = false

[auth.external.apple]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"

[auth.external.google]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"

[edge_runtime]
enabled = true