/**
 * Generates public/sitemap.xml and public/robots.txt from a single source.
 *
 * The host comes from VITE_SITE_URL (falling back to the current production
 * host) so moving the site onto a custom domain is an environment change, not
 * a code change. The previous hand-maintained sitemap had drifted from the SEO
 * constants in src/lib/seo.tsx, and 77 of its 79 URLs pointed at paths that
 * render the 404 page because the app has no routes for them.
 *
 * Run via `npm run seo:generate`, or automatically before `npm run build`.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITEMAP_ROUTES } from './sitemap-routes.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const SITE_URL = (process.env.VITE_SITE_URL || 'https://itukarua3.vercel.app').replace(/\/+$/, '');

/** Routes that exist but must never be indexed or crawled. */
const DISALLOW = ['/dashboard', '/admin', '/inbox', '/api/', '/auth/'];

/** Paths that are filtered out of crawling rather than blocked outright. */
const DISALLOW_PATTERNS = ['/*?page=', '/*?search=', '/*?category=', '/*?county='];

/**
 * Public paths a crawler may follow explicitly. Kept in sync with
 * SITEMAP_ROUTES: the app has no /jobs or /services route, so allowing those
 * here would only invite crawlers onto the 404 page.
 */
const INDEXABLE = SITEMAP_ROUTES.map((route) => route.path);

const escapeXml = (value) =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const today = new Date().toISOString().slice(0, 10);

const urlEntries = SITEMAP_ROUTES.map((route) => {
  const loc = escapeXml(`${SITE_URL}${route.path}`);
  return [
    '  <url>',
    `    <loc>${loc}</loc>`,
    `    <lastmod>${today}</lastmod>`,
    `    <changefreq>${route.changefreq}</changefreq>`,
    `    <priority>${route.priority.toFixed(1)}</priority>`,
    '  </url>',
  ].join('\n');
}).join('\n');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

const robots = `# Itukarua - Kenya's Local Jobs & Classifieds Platform
# Generated by scripts/generate-seo.mjs. Edit SITEMAP_ROUTES / DISALLOW there,
# not this file.
# ${SITE_URL}

User-agent: *
Allow: /
${DISALLOW.map((path) => `Disallow: ${path}`).join('\n')}
${DISALLOW_PATTERNS.map((pattern) => `Disallow: ${pattern}`).join('\n')}

User-agent: Googlebot
Allow: /
${INDEXABLE.map((path) => `Allow: ${path}`).join('\n')}
${DISALLOW.map((path) => `Disallow: ${path}`).join('\n')}

User-agent: Bingbot
Allow: /
${INDEXABLE.map((path) => `Allow: ${path}`).join('\n')}
${DISALLOW.map((path) => `Disallow: ${path}`).join('\n')}

User-agent: Twitterbot
Allow: /

User-agent: facebookexternalhit
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`;

writeFileSync(join(ROOT, 'public', 'sitemap.xml'), sitemap, 'utf8');
writeFileSync(join(ROOT, 'public', 'robots.txt'), robots, 'utf8');

console.log(`seo: generated sitemap.xml (${SITEMAP_ROUTES.length} urls) and robots.txt for ${SITE_URL}`);
